separator = ":"
compound = "|"
end = "\n"

[version]
  major = 1
  minor = 0
  patch = 0

[category]
  get = "G"
  set = "S"
  ack = "A"
  nak = "N"
  sub = "B"
  pub = "P"

[[data]]
  [data.item-1]
    addr = "0000"
    [[data.item-1.data]]
      [data.item-1.data.child-1]
        [[data.item-1.data.child-1.data]]
          grand-child-1 = { type = "u8" }
        [[data.item-1.data.child-1.data]]
          grand-child-2 = { type = "float" }
    [[data.item-1.data]]
      child-2 = { type = "none" }
[[data]]
  item-2 = { addr = "2000", type = "none" }

